//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vetclinic.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public int IdAuth { get; set; }
        public int IdUser { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual User User { get; set; }
    }
}
